### ISSUE TITLE
CUDA 13.3

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1393]
CUDA 13.3 has been released

We should test FLAME GPU with CUDA 13.3, and add it to our CI workflows.

It will be simplest to do this after #1375 else they will conflict. 

> [!NOTE]
> On Ubuntu for local installations, the `cccl-13-3` apt package is marked as `Breaks:` `cuda-cccl-12-0` through `cuda-cccl-12-9`, which is very annoying for local machines with multipple CUDA's instaled. 
> We will have to use runfile installers to get around this, or switch to container-based workflows locally for mutli-version development 😢

**Comment by ptheywood** [comment]
The apt package for `cccl-13-3` no longer appears to be marked as breaking/conflicting with cccl 12.x packages 🎉 

On my home machine (Ubuntu 25.10) with GCC 15.2, c++ FLAME GPU building fine and the test suite passes (I have not checked python). 
The `flamegpu` target also builds with GCC 13.4 & 12.5 also successfully. 

--- 

On my office machine (Ubuntu 24.04) with GCC 13.3 (or 12.4) compilation errrors were encountered within CCCL (both in currrent `master` and `amdgpu` branches). 


```
/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/__device/arch_id.h(71): error: template constraint not satisfied
    };
     ^
/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/std/array(398): note #3135-D: substitution of arguments "<cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id>" for requires-clause failed
  requires (is_same_v<_Tp, _Args> && ...)
                                  ^
/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/std/array(398): note #3042-D: atomic constraint not constant
  requires (is_same_v<_Tp, _Args> && ...)
                                  ^
/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/std/array(398): note #2721-D: expression cannot be interpreted
  requires (is_same_v<_Tp, _Args> && ...)
                                  ^

/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/__device/arch_id.h(66): error: no instance of constructor "cuda::std::__4::array" matches the argument list
            argument types are: (cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id, cuda::__4::arch_id)
    return ::cuda::std::array{
                             ^

/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/__device/arch_id.h(66): error: cannot deduce class template arguments
    return ::cuda::std::array{
           ^

/usr/local/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/__device/arch_id.h(67): error: too many initializer values
      arch_id::sm_60, arch_id::sm_61, arch_id::sm_62, arch_id::sm_70, arch_id::sm_75, arch_id::sm_80,

```


In the upstream repository, the offending code is no longer in the development branch / next release, having been replaced by alternate functionality in general. It is unclear if this is because this was a known issue or not. 

I'll have to spend some more time lookin into this later / see if it is an issue specifically with my office machine, with 24.04 installations in general or something else (i.e. see if I can reproduce this on ubuntu 24.04-based CI), but atleast in princial our code appears fine under 13.3.

**Comment by Geremia** [comment]
@ptheywood I get "[`arch_id.h: error: template constraint not satisfied`](https://github.com/pytorch/pytorch/issues/186405)," too, when trying to compile Pytorch 2.13.0 with CUDA 13.3.1.

**Comment by Geremia** [comment]
This is a CUDA issue, fixed with:
```patch
--- a/opt/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/__device/arch_id.h
+++ b/opt/cuda-13.3/targets/x86_64-linux/include/cccl/cuda/__device/arch_id.h
@@ -66 +66 @@
-  return ::cuda::std::array{
+  return ::cuda::std::array<arch_id, 22>{
```
(Your `arch_id.h`'s exact path might be different.)
